### ISSUE TITLE
Enable EditorConfig spec test through editorconfig-core-test

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4j#1]
See https://github.com/editorconfig/editorconfig-core-test

**Comment by ppalaga** [comment]
Some work in progress here https://github.com/ppalaga/ec4j/commits/i1 . Note that the branch is on top of PR #3 
The initial score is `21% tests passed, 144 tests failed out of 182`.  I did not have much time to look into the details yet.

**Comment by angelozerr** [comment]
Ok I have enable ctests and me I have `14% tests passed, 154 tests failed out of 180`

Very bad score -( I will try to improve that.

**Comment by ppalaga** [comment]
The most valuable output of the tests is in `Testing/Temporary/LastTest.log`. Good luck!
