### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/ec4j#16]
@ppalaga I have a doubt to adapt MIT license because I have copied/paste some code (for glob) https://github.com/editorconfig/editorconfig-core-java/blob/master/src/main/java/org/editorconfig/core/EditorConfig.java from at https://github.com/angelozerr/ec4j/blob/master/src/main/java/org/eclipse/ec4j/model/RegexpUtils.java

**Comment by ppalaga** [comment]
Disclaimer: I am not a lawyer.

Apache License 2.0 does not completely exclude this. Citing from ASF FAQ [1]:

> You may distribute the result under a different license, but you need to acknowledge the use of the Foundation's software.

I am not quite sure sure how to implement this in your particular case. (1) Keeping the original license header, (2) giving credit to the original author in the JavaDoc and (3) documenting your changes should be safe. 

For (1) we'd have to add an `<exclusion>` to the license plugin https://github.com/angelozerr/ec4j/blob/master/pom.xml#L105

[1] http://www.apache.org/foundation/license-faq.html#Distribute-changes

**Comment by angelozerr** [comment]
@ppalaga perhaps the best solution is to move to ASF to avoid having trouble?

> we'd have to add an <exclusion> to the license plugin 

Have you time to do that?

**Comment by ppalaga** [comment]
> the best solution is to move to ASF

You mean change the ec4j project's license to Apache License 2.0? - Yes, I can do that.

**Comment by angelozerr** [comment]
> You mean change the ec4j project's license to Apache License 2.0? 

Yes, please.
