### ISSUE TITLE
Properly implement IEditorConfigHandler.[start|end]OptionValue() in EditorConfigHandlerAdapter

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4j#17]
As of 4f96922e91c0888595b893a65805e6a5eb0184e2  `EditorConfigHandlerAdapter` 

has 

```
	@Override
	public void startOptionValue(Object option, String name) {

	}

	@Override
	public void endOptionValue(Object option, String value, String name) {

	}
```

`Object option` should be `Option option` in both cases. Otherwise, the code does not compile on Oracle JDK 8.

A PR follows.

**Comment by angelozerr** [comment]
@ppalaga I think I have fixed this problem. Please get the source from master. Sorry for this problem -(

**Comment by ppalaga** [comment]
Fixed by 60e4fce15cc48b43444b1318b7fcad2888539ebd

**Comment by ppalaga** [comment]
> I think I have fixed this problem. Please get the source from master. Sorry for this problem -(

No problem, but so that things like this one, or #19 do not happen in the future, I propose you to start letting somebody else to review your own changes. I do this for my own projects too. I can review, if you are interested. Just name me in your PR.

**Comment by ppalaga** [comment]
BTW, the status on Linux, with the current master 68ffa825bba3b5d128d581711b3d61af9ea56a21 is

```
97% tests passed, 5 tests failed out of 182

Total Test time (real) =  12.74 sec

The following tests FAILED:
         63 - braces_escaped_backslash2 (Failed)
         85 - braces_alpha_range1 (Failed)
        162 - max_section_name_ignore (Failed)
        169 - root_file_mixed_case (Failed)
        178 - backslash_not_on_windows (Failed)
Errors while running CTest
```

**Comment by angelozerr** [comment]
> Good job!

Thanks @ppalaga !

Hope I will understand how to fix other tests.
