### ISSUE TITLE
Define prefered indentation character and line endings using Checkstyle.

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4j#21]
I propose to introduce a few basic checkstyle checks, so that all contributors are forced to use the same line endings, same indentation character, no trailing spaces, etc.

Most of the files currently use tab for indentation and Windows ends of lines. Before I prepare a PR, I wanted to make sure that you @angelozerr really prefer crlf and tabs. 

I am asking this because these are not the most common settings in the Java space. Having unusual settings makes contributing harder (speaking for myself).

**Comment by angelozerr** [comment]
>  I wanted to make sure that you @angelozerr really prefer crlf and tabs.

To be honnest with you, I have none preference. I'm using just the JDT standard preferences. If you change preferences, perhaps it will be good to store Eclipse preferences?

We could host too an `.editorconfig` file even if JDT cannot support it, for ther IDE it could help them. No?

**Comment by ppalaga** [comment]
> If you change preferences, perhaps it will be good to store Eclipse preferences?

While it is common (at least in my social bubble) that projects share their preferred formatting in form of exported IDE config files (see e.g. [1]), it is generally impractical to maintain any IDE specific project files in git as a part of the main source tree. It is fully up to the given contributor which specific IDE/IDE version or editor he takes. Note that Eclipse is not the only Java IDE, there are many others. It would cause a huge maintenance overhead to enforce the formatting via IDE specific settings.

Esp. checking in Eclipse project files causes issues as long as individual contributors are not bound to use the very same Eclipse version with the very same set set of plugins installed. Otherwise you can break my setup by checking in your config that is incompatible with a newer/older version of my plugin, etc.

The best practice IMO, is that the CI is the golden standard that both defines and enforces the formatting. All IDE configs (if at all) offered to contributors are just ancillary.

Clearly, this is exactly the area targeted by EditorConfig. I like EditorConfig very much for its simplicity and portability across IDEs and build tools. I hope some day in a not very distant future, any new project I'll check out will have `.editorconfig` and both my IDE and project's CI will honor it :)

As long as we we do not have EditorConfig working well in Java space, we are doomed to use tools like Checkstyle. I do not think it is worth ignoring the problem for now. Broken indentation, ends of lines and trailing whitespace are annoying enough in the long run. It is best to take care for the setup at the very beginning.

> We could host too an .editorconfig file even if JDT cannot support it, for ther IDE it could help them. No?

+1, although it would indeed be a rather symbolic step, given that none of us uses any tool that would honor it.

> To be honnest with you, I have none preference. I'm using just the JDT standard preferences.

OK, then I'll take four spaces and Unix EoL, the dominant combination in the Java space, unless you protest loudly ;)

[1] https://github.com/wildfly/wildfly-core/tree/master/ide-configs
