### ISSUE TITLE
Split ec4j into core and services

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4j#28]
I propose to move the `org.eclipse.ec4j.completion` and `org.eclipse.ec4j.validation` packages (plus a few other related classes) back to ec4e. 

Motivation: The current completion and validation functionality is designed in the way usual for Eclipse plugins (although it tries to be generic). I am sure it will not be needed in the maven plugin I work on and I quite doubt that any other IDE's plugin would benefit from it. Keeping it here in ec4j would cause an unnecessary maintenance overhead and once the code is moved to ec4e, it could be simplified substantially through making it less generic and more tightly bound to Eclipse APIs. 

What is your opinion, @angelozerr ?

**Comment by ppalaga** [comment]
https://github.com/angelozerr/ec4j/pull/29 contains the proposal in form of a pull request.

**Comment by angelozerr** [comment]
> Motivation: The current completion and validation functionality is designed in the way usual for Eclipse plugins

Are you sure with that? My idea was to provide IDE services like language service does. In the future we could transform thoses services with lsp4j interface and provides a real language server for editorconfig.

My idea was to provide an another editorconfig parser with location and IDE services inside ec4j.

But it seems you don't like this idea?

**Comment by ppalaga** [comment]
>> Motivation: The current completion and validation functionality is designed in the way usual for Eclipse plugins

> Are you sure with that? 

I am sure I do not need that functionality in my maven plugin, but I am not so sure for other IDEs and the way they work and prefer getting things :) You may well be right that other IDEs will be happy to consume validation and completion in this form. My way of thinking for other IDEs was simply "hm... this looks like the code I saw in Shelled and other Eclipse plugins -- it would be rather a random luck that other IDEs want it in this way. Would it not be a much safer bet not to aim at something we do not know enough about?".

> My idea was to provide IDE services like language service does. In the future we could transform thoses services with lsp4j interface and provides a real language server for editorconfig.

I like the idea of having `.editorconfig` as a language server. But I still think that things required by lsp4j do not necessarily have to live in the core `ec4j` module. I consider it cleaner the core `ec4j` module to contain just the model, parser and treewalking functionality, while the validation and completion would live elsewhere (be it in ec4e or in another separate source tree or perhaps as a separate module in `ec4j`).

When dividing functionality into modules and projects, considering which parts can/will be used separately is one of the important concerns (testability, maintainability and size being others). I'd like to state again that I prefer to get a well performing and well tested editorconfig treewalker for my maven plugin and that at this stage, I am not interested in the validation and completion.

I see that your perspective might be different. Whatever specific result comes out of this discussion, hopefully, the general scope (what it is and what it is not) and direction of `ec4j` will become a bit cleaner to both you, me and other potential users and contributors.

**Comment by angelozerr** [comment]
I think the main problem @ppalaga is that we have not the same goal:) You wish consume just ec4j parser. Me I need to have IDE features like validation, completion, hover, etc.

I understand your mind and perhaps ec4j should host 2 projects:

 * org.eclipse.ec4j.core (today org.eclipse.ec4j)
 * org.eclipse.ec4j.ide which provides IDE features like compeltion, validation. 

What do you think about that?

**Comment by ppalaga** [comment]
> I understand your mind and perhaps ec4j should host 2 projects:
>
> * org.eclipse.ec4j.core (today org.eclipse.ec4j)
> * org.eclipse.ec4j.ide which provides IDE features like compeltion, validation.

Sounds as a good compromise. Thanks, @angelozerr !

I'll try to align the above PR with this outcome.

While I like  the `org.eclipse.ec4j.core` name, `org.eclipse.ec4j.ide` is not that perfect, but I do not have a better idea. Unless you or me suggests anything better, I'll just use `org.eclipse.ec4j.ide`.

**Comment by ppalaga** [comment]
What I do not like about `org.eclipse.ec4j.ide`: It is not an IDE what will live inside. It is rather some sort of "IDE support services" - which is too long and descriptive.

**Comment by angelozerr** [comment]
> Sounds as a good compromise. Thanks, @angelozerr !

Cool!

>  It is rather some sort of "IDE support services" - which is too long and descriptive.

I totally agree, I don't like "ide", perhaps it should be better "services" ? Any idea are welcome!

**Comment by ppalaga** [comment]
OK, be it services.

**Comment by angelozerr** [comment]
Great @ppalaga and thanks for your PR, but have you a PR for ec4e which uses the 2 new plugins and new packages?

**Comment by ppalaga** [comment]
> have you a PR for ec4e which uses the 2 new plugins and new packages?

I have this branch of ec4e https://github.com/ppalaga/ec4e/tree/171025-ec4j-split that consumes revision 9f9413c from my ec4j branch https://github.com/ppalaga/ec4j/commits/i31 . The 171025-ec4j-split compiles, but I have not run the code in any way (no time and don't know how).

**Comment by angelozerr** [comment]
> The 171025-ec4j-split compiles, but I have not run the code in any way (no time and don't know how).

I will do that no problem. I would liek just clarify the instance problem like https://github.com/ppalaga/ec4e/commit/5d17d41e798e628ec93e0f353ba5c84c0d6b441b#commitcomment-25201815 Is it a real problem?

**Comment by ppalaga** [comment]
Replied there.
