### ISSUE TITLE
Introduce EditorConfigSession and simplify the document access

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4j#31]
`EditorConfigSession` is basically a new name for the current `AbstractEditorConfigManager` and `EditorConfigManager`. I find the word "session" good because it implies some life cycle and state, that this kind of object inevitably has to have. A user of our API is supposed to create an `EditorConfigSession` to query files for the applicable EditorConfig options. The user should have the freedom to decide for how long he wants the session to keep alive and which specific caching strategy the session should use.

The user would typically call something like:

```
Cache myCache = ...;
EditorConfigSession mySession = EditorConfigSession.builder()
        .cache(myCache)
        .rootDirectory(ResourcePaths.ofPath(Paths.get("/my/dir1")))
        .build();
Collection<Option> opts1 = mySession.queryOptions(Resources.ofPath(Paths.get("/my/dir1/Class1.java")));
Collection<Option> opts2 = mySession.queryOptions(Resources.ofPath(Paths.get("/my/dir1/Class2.java")));
```

For the document access, it could be proposed separately, but such separation would mean too much overhead for me. Therefore I am submitting this together with the `EditorConfigSession` part.

Currently, we have `ContentProvider<T>` responsible for reading out of documents, that are kept generic. There is no `Document` interface that would define the way we want to read. All is supposed to be done in the `ContentProvider`. I do not find this good because 

(1) This pollutes the API with unnecessary generics. We not only need a special `ContentProvider` for File access (that would be OK), but we also need a special subtype of `AbstractEditorConfigManager` for it which I think is not necessary.

(2) This forces us to pass both `ContentProvider` and document throughout the API - e.g. in `EditorConfigService`. One argument could be enough.

Proposal: introduce a `Resource` interface that would specify how we want to read documents. We'll provide a few common implementations for reading from files, from static string, etc. 
This will simplify the high level API.

I have implemented this proposal and I'll paste a link soon.

**Comment by ppalaga** [comment]
This commit implements the proposal: https://github.com/ppalaga/ec4j/commit/91ccfd10db675b33d9698d60be2985cee27c71c3 

I can submit it as a PR after #29 is merged and after #30 is resolved.

WDYT, @angelozerr ?

**Comment by ppalaga** [comment]
And I forgot to mention that with https://github.com/ppalaga/ec4j/commit/91ccfd10db675b33d9698d60be2985cee27c71c3 only one last test is not passing:

```
99% tests passed, 1 tests failed out of 182

Total Test time (real) =  15.48 sec

The following tests FAILED:
         85 - braces_alpha_range1 (Failed)
```

**Comment by angelozerr** [comment]
The best mean to validate the API is to see ec4e. Using Resource is more cleaner, I agree but how it works with Eclipse API (ec4e). It means that you need to create an instance of Resource each time ec4e consumes completion, hover, etc. 

My idea with ContentProvider is to have a singleton which implements ContentProvider  for Document to consume ec4j. My fear with your new design is to create an instance every time.

Have you a PR which refactor ec4e with your new design?

**Comment by angelozerr** [comment]
I forget to say you, that I love your API which looks like Stream (of).

**Comment by ppalaga** [comment]
> The best mean to validate the API is to see ec4e. 

Yes, it is doable, see my ec4e branch  https://github.com/ppalaga/ec4e/tree/171025-ec4j-split that consumes revision 9f9413c from my ec4j branch https://github.com/ppalaga/ec4j/commits/i31 .

> Using Resource is more cleaner, I agree but how it works with Eclipse API (ec4e). It means that you need to create an instance of Resource each time ec4e consumes completion, hover, etc.

Yes, and I do think that's an overhead we need to care for.

> My idea with ContentProvider is to have a singleton which implements ContentProvider for Document to consume ec4j. My fear with your new design is to create an instance every time.

It is a thin wrapper that should get GC'ed fast.

> Have you a PR which refactor ec4e with your new design?

Yes, see above.

**Comment by angelozerr** [comment]
> It is a thin wrapper that should get GC'ed fast.

What do you mean? My question was: is it a real problem to create an instance every time?

**Comment by ppalaga** [comment]
As I said, in Java, it is OK to create a small easily GC-able object every now and then. Hovers and completions do not happen often enough to see any perceivable impact.
