### ISSUE TITLE
Prefer AsciiDoc to Markdown

### ISSUE THREAD

**Issue by ppalaga** [angelozerr/ec4j#4]
I find AsciiDoc [1] more rich and cleaner as compared to Markdown. I admit this is highly subjective and will not be surprised if you reject this for subjective reasons :).

A PR will follow.

[1] https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/asciidoc-vs-markdown.adoc

**Comment by angelozerr** [comment]
I don't know AsciiDoc, but I'm aware to discover new things. Any PR are welcome, thanks
