### ISSUE TITLE
EditorConfig, Section, Option with location

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/ec4j#42]
Today completion, validation,hover, parse each time the editorconfig content. It should be better to use an AST EditorConfig instance to do that (like JDT does with ICompilationUnit).

In other words the IDE maintains an instance of EditorConfig and use it for IDE services like completion, validation, hover, codelens, folding, etc

To do that the EditorConfig, Section, Option class must have start/end location. But @ppalaga I know that you don't need this location info. Here my proposition:

 * add withLocation(boolean) to the parser to store or not the location
 * add Section#start, Section#end, etc which are null when  withLocation(false) or create SectionAndLoc which extends Section.

@ppalaga what do you think about that?

**Comment by ppalaga** [comment]
I understand the need for the `Location` info in IDE classes. 

As for whether the default model should be Location aware, I'd spontaneously say no, unless there is no acceptable (for you) way to do it differently. Let me form my definitive view during the preparation of the PR to adapt ec4e for the latest changes in ec4j.

**Comment by angelozerr** [comment]
Now you have done a big refactoring with API, could we discuss again about this location topic?

I would like to manage a single instance of EditorConfig updated with Eclipse IReconciler and use this instance for IDE features like validation, completion, codelens, outline, folding to avoid parsing .editorconfig for each IDE feature.

**Comment by ppalaga** [comment]
For which exact parts of the model you need locations? I saw it for 

* property name start
* property value start

Anywhere else?

**Comment by ppalaga** [comment]
It should be quite easy to create a new Handler that would produce a location aware flavor of the model.  I could do that. The question is where those new classes should be located? I'd put them where they would be used - i.e. to ec4e. WDYT?

**Comment by angelozerr** [comment]
> For which exact parts of the model you need locations? I saw it for

I need start / end location for :

 * property name (for completion, validation, hover)
 * property value (for completion, validation, hover)
 * section (for codelens, folding) and better end of enclosed section for folding
 * comments (for folding)

> It should be quite easy to create a new Handler that would produce a location aware flavor of the model. I could do that. 

Very cool!

> The question is where those new classes should be located? I'd put them where they would be used - i.e. to ec4e. WDYT?

In ec4j services. I would like to provide the capability to load EditorConfig instance with location and existing validation, completion, hover will be based on this instance.

**Comment by ppalaga** [comment]
Let's focus on locations in this issue and let's move comments to a new issue https://github.com/angelozerr/ec4j/issues/54
